export const SESSION_JWT_TTL_SECONDS = 7 * 24 * 60 * 60;
export const REMEMBERED_SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;
export const REMEMBERED_COOKIE_MAX_AGE_MS = REMEMBERED_SESSION_TTL_SECONDS * 1000;
