import type { Issue, IssueAssignee } from "@/feature/issues/types";

export const mockIssueAssignees: IssueAssignee[] = [
  { id: "user-amina", name: "Amina Yusuf" },
  { id: "user-daniel", name: "Daniel Kim" },
  { id: "user-maya", name: "Maya Chen" },
  { id: "user-theo", name: "Theo Martins" },
];

export const mockIssues: Issue[] = [
  {
    id: "issue-214",
    identifier: "TF-214",
    title: "Preserve upload progress when the connection drops",
    status: "todo",
    priority: "urgent",
    assignee: mockIssueAssignees[0],
    dueDate: "2026-09-08",
    commentCount: 6,
    updatedAt: "2026-09-05T00:45:00.000Z",
  },
  {
    id: "issue-219",
    identifier: "TF-219",
    title: "Clarify permission states for workspace guests",
    status: "todo",
    priority: "high",
    assignee: null,
    dueDate: "2026-09-11",
    commentCount: 3,
    updatedAt: "2026-09-04T15:20:00.000Z",
  },
  {
    id: "issue-224",
    identifier: "TF-224",
    title: "Add issue links to the weekly digest email",
    status: "todo",
    priority: "low",
    assignee: mockIssueAssignees[1],
    dueDate: null,
    commentCount: 1,
    updatedAt: "2026-09-03T09:10:00.000Z",
  },
  {
    id: "issue-226",
    identifier: "TF-226",
    title: "Document the workspace handoff checklist",
    status: "todo",
    priority: "medium",
    assignee: mockIssueAssignees[3],
    dueDate: "2026-09-17",
    commentCount: 2,
    updatedAt: "2026-09-01T16:40:00.000Z",
  },
  {
    id: "issue-207",
    identifier: "TF-207",
    title: "Improve keyboard navigation in command search",
    status: "in_progress",
    priority: "high",
    assignee: mockIssueAssignees[2],
    dueDate: "2026-09-07",
    commentCount: 8,
    updatedAt: "2026-09-05T01:05:00.000Z",
  },
  {
    id: "issue-218",
    identifier: "TF-218",
    title: "Keep active filters when returning to the board",
    status: "in_progress",
    priority: "medium",
    assignee: mockIssueAssignees[3],
    dueDate: "2026-09-14",
    commentCount: 4,
    updatedAt: "2026-09-04T12:35:00.000Z",
  },
  {
    id: "issue-221",
    identifier: "TF-221",
    title: "Align empty states across workspace settings",
    status: "in_progress",
    priority: "medium",
    assignee: null,
    dueDate: null,
    commentCount: 2,
    updatedAt: "2026-09-02T18:15:00.000Z",
  },
  {
    id: "issue-205",
    identifier: "TF-205",
    title: "Resolve duplicate alerts after reconnecting",
    status: "in_progress",
    priority: "urgent",
    assignee: mockIssueAssignees[1],
    dueDate: "2026-09-09",
    commentCount: 11,
    updatedAt: "2026-08-31T14:25:00.000Z",
  },
  {
    id: "issue-198",
    identifier: "TF-198",
    title: "Add activity context to assignment notifications",
    status: "done",
    priority: "medium",
    assignee: mockIssueAssignees[0],
    dueDate: "2026-09-02",
    commentCount: 7,
    updatedAt: "2026-09-05T00:15:00.000Z",
  },
  {
    id: "issue-203",
    identifier: "TF-203",
    title: "Reduce layout shift while issue details load",
    status: "done",
    priority: "high",
    assignee: mockIssueAssignees[1],
    dueDate: "2026-09-04",
    commentCount: 5,
    updatedAt: "2026-09-04T10:50:00.000Z",
  },
  {
    id: "issue-211",
    identifier: "TF-211",
    title: "Standardize labels in the member invitation flow",
    status: "done",
    priority: "low",
    assignee: mockIssueAssignees[2],
    dueDate: null,
    commentCount: 2,
    updatedAt: "2026-09-03T08:30:00.000Z",
  },
  {
    id: "issue-190",
    identifier: "TF-190",
    title: "Make issue identifiers easier to scan in tables",
    status: "done",
    priority: "low",
    assignee: mockIssueAssignees[3],
    dueDate: "2026-08-29",
    commentCount: 3,
    updatedAt: "2026-09-01T11:45:00.000Z",
  },
  {
    id: "issue-194",
    identifier: "TF-194",
    title: "Improve the confirmation copy after inviting members",
    status: "done",
    priority: "medium",
    assignee: null,
    dueDate: null,
    commentCount: 4,
    updatedAt: "2026-08-30T17:20:00.000Z",
  },
];
